# Generated by Django 3.1.7 on 2021-03-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='image',
            new_name='images',
        ),
    ]
