# Generated by Django 3.1.7 on 2021-03-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210316_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='images',
            new_name='image',
        ),
    ]
