# Generated by Django 3.1.7 on 2021-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210317_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
