# Generated by Django 3.1.7 on 2021-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_imagealbum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_model', to='products.imagealbum'),
        ),
    ]
