# Generated by Django 3.1.7 on 2021-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210316_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
