# Generated by Django 3.1.7 on 2021-03-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210316_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no_of_rating',
            new_name='no_of_ratings',
        ),
    ]
