# Generated by Django 3.1.7 on 2021-04-15 18:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210415_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
