# Generated by Django 3.1.7 on 2021-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210419_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(default='None variant', max_length=100),
        ),
    ]
