# Generated by Django 3.1.7 on 2021-04-21 20:12

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210420_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_of_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(default='Anonymous', max_length=40)),
                ('rating', products.models.IntegerRangeField()),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
