# Generated by Django 3.1.7 on 2021-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210422_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=25),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
